apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm-disagg-router-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Increase timeouts for LLM inference (disaggregated takes longer)
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "500"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "100"
spec:
  ingressClassName: nginx
  rules:
    - host:
      http:
        paths:
          - path: /vllm-disagg-router(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: vllm-disagg-router-frontend
                port:
                  number: 8000
