# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: profile-sla
  namespace: dynamo-cloud
spec:
  template:
    spec:
      serviceAccountName: profile-sla-sa
      tolerations:
      - key: "nims/node-type"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: nodepool
                operator: In
                values:
                - h100
      containers:
      - name: profile-sla
        image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.4.0
        resources:
          requests:
            cpu: "16"
            memory: "10Gi"
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: HF_TOKEN
          - name: NATS_SERVER
            value: nats://dynamo-platform-nats:4222
          - name: ETCD_ENDPOINTS
            value: dynamo-platform-etcd:2379
        command: ["python", "/workspace/benchmarks/profiler/profile_sla.py"]
        args:
          - --config
          -  /workspace//profiling_results/disagg.yaml
          - --output-dir
          - /workspace/profiling_results
          - --namespace
          - dynamo-cloud
          - --backend
          - vllm
          - --min-num-gpus-per-engine
          - "1"
          - --max-num-gpus-per-engine
          - "2"
          - --isl
          - "3000"
          - --osl
          - "150"
          - --ttft
          - "200"
          - --itl
          - "20"
        volumeMounts:
          - name: output-volume
            mountPath: /workspace/profiling_results
      restartPolicy: Never
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: profiling-pvc
  backoffLimit: 0
